### ISSUE TITLE
The instructions have decayed

### ISSUE THREAD

**Issue by lwassermann** [LivelyKernel/lively-vagrant#1]
The two-step vagrant init, then vagrant up does not work anymore, because the box seems to be unfindable. If you go down the rabbit hole of trying to find it manually you end up following:
https://vagrantcloud.com/rksm/boxes/lively/versions/0.1.1/providers/virtualbox.box
which redirects to 
http://lively-web.org/web/vagrant/2014-06-24_lively-debian7.box
Unfortunately, that file does not exist anymore.
The same error occured for me when trying to reprovision a new box, so the fault might lay with my system. Can anybody reproduce the problem using the instructions?

```
mkdir -p ~/LivelyBox && cd ~/LivelyBox
vagrant init rksm/lively
vagrant up
```

**Comment by rksm** [comment]
Ay, gonna look into that. Also, [lively docker](https://github.com/LivelyKernel/lively-docker) might be an alternative.

**Comment by rksm** [comment]
Actually, given that we are only using docker now and that docker allows to be used similarly to vagrant I will probably not fix things soon. In case you would like to repair the vagrant image you can just pick a docker container and then take the Dockerfile as a reference for a setup script.

**Comment by lwassermann** [comment]
I don't actually care about vagrant over docker or any other vm-building scripts. I simply followed the instructions on the README.md of lively kernel and there is no mention there of docker. I'll try docker tomorrow night :-)

**Comment by kansasSamurai** [comment]
Maybe remove vagrant from the readme?  I went down this rabbithole as well.  I guess I don't technically care between Vagrant and Docker either as I am new to both but I started with Vagrant which seems ultra easy to install and run and I like the VM approach.  Oh well... I guess I am going to learn Docker better now.
